"use strict";if(typeof enlightenment_infinite_scroll_args!='undefined'){var vw=jQuery(window).width();enlightenment_infinite_scroll_args['bufferPx']=jQuery(window).height()*2;delete enlightenment_infinite_scroll_args['loading']['img'];}
var raf=requestAnimationFrame||mozRequestAnimationFrame||webkitRequestAnimationFrame||msRequestAnimationFrame;function graceunderpressure_affix_navbar(navbar_height,footer_height,margin_top){(function($){if(window.scrollY>=margin_top){$('.site-header').removeClass('navbar-static-top');$('.site-header').addClass('navbar-fixed-top');$('.site-header').css('top',-margin_top);}else{$('.site-header').removeClass('navbar-fixed-top');$('.site-header').addClass('navbar-static-top');$('.site-header').css('top','');}})(jQuery);return false;}
function graceunderpressure_ajax_state(event,link,popstate){event.preventDefault();event.stopPropagation();var $this=jQuery(this),$post=$this.closest('.hentry');var offset=0;popstate=typeof popstate!=='undefined'?popstate:false;link=typeof link!=='undefined'?link:$this.attr('href').split('#')[0];if(!popstate){offset=$post.offset().top;}
$this.addClass('loading');(function($){$('#primary').infinitescroll('destroy');$.get(link,{},function(data){if(!popstate&&typeof history.pushState!='undefined'){history.pushState(data,'Page',link);}
document.title=$(data).filter('title').text();document.body.setAttribute('class',new DOMParser().parseFromString(data,"text/html").body.getAttribute('class'));if(!popstate){$('html, body').scrollTop(window.scrollY- offset);}else{$('html, body').scrollTop(0);}
$('#content').html($('#content',data).html());$('.navbar-nav').html($('.navbar-nav',data).html());$('.more-link').on('click',graceunderpressure_ajax_state);});})(jQuery);}
function graceunderpressure_sticky_header(event,items,st,lastScrollTop,wh){(function($){var target=$(event.target).closest('.hentry');var items=$('.hentry');if(lastScrollTop<st){var target=items.get(0);items.each(function(){if(st<$(this).offset().top&&st>=0){return false;}
target=$(this);});if(st>=target.offset().top){target.prev('.hentry').children('.entry-header').removeClass('entry-header-top');target.prev('.hentry').children('.entry-header').removeClass('entry-header-active');target.prev('.hentry').children('.entry-header').addClass('entry-header-bottom');$('.entry-header',target).removeClass('entry-header-bottom');$('.entry-header',target).removeClass('entry-header-top');$('.entry-header',target).addClass('entry-header-active');target.next('.hentry').children('.entry-header').removeClass('entry-header-active');target.next('.hentry').children('.entry-header').removeClass('entry-header-bottom');target.next('.hentry').children('.entry-header').addClass('entry-header-top');}
if(st>=target.offset().top+ target.height()- wh){target.prev('.hentry').children('.entry-header').removeClass('entry-header-top');target.prev('.hentry').children('.entry-header').removeClass('entry-header-active');target.prev('.hentry').children('.entry-header').addClass('entry-header-bottom');$('.entry-header',target).removeClass('entry-header-top');$('.entry-header',target).removeClass('entry-header-active');$('.entry-header',target).addClass('entry-header-bottom');target.next('.hentry').children('.entry-header').removeClass('entry-header-active');target.next('.hentry').children('.entry-header').removeClass('entry-header-bottom');target.next('.hentry').children('.entry-header').addClass('entry-header-top');}}else{var target=items.get(items.length- 1);items.each(function(){target=$(this);if(target.offset().top+ target.height()>=st+ wh){return false;}});if(target.offset().top+ target.height()>st+ wh){target.prevAll('.hentry:first').children('.entry-header').removeClass('entry-header-top');target.prevAll('.hentry:first').children('.entry-header').removeClass('entry-header-active');target.prevAll('.hentry:first').children('.entry-header').addClass('entry-header-bottom');$('.entry-header',target).removeClass('entry-header-top');$('.entry-header',target).removeClass('entry-header-bottom');$('.entry-header',target).addClass('entry-header-active');target.next('.hentry').children('.entry-header').removeClass('entry-header-active');target.next('.hentry').children('.entry-header').removeClass('entry-header-bottom');target.next('.hentry').children('.entry-header').addClass('entry-header-top');}
if(target.offset().top>=st){target.prev('.hentry').children('.entry-header').removeClass('entry-header-top');target.prev('.hentry').children('.entry-header').removeClass('entry-header-active');target.prev('.hentry').children('.entry-header').addClass('entry-header-bottom');$('.entry-header',target).removeClass('entry-header-active');$('.entry-header',target).removeClass('entry-header-bottom');$('.entry-header',target).addClass('entry-header-top');target.next('.hentry').children('.entry-header').removeClass('entry-header-active');target.next('.hentry').children('.entry-header').removeClass('entry-header-bottom');target.next('.hentry').children('.entry-header').addClass('entry-header-top');}}})(jQuery);return false;}
function graceunderpressure_sticky_header_callback(items){(function($){if($('.blog.blog-design-blog .hentry').length>1){var lastScrollTop=0;var wh=$(window).height();var tick=false;window.addEventListener('scroll',function(event){var e=event;if(!tick&&raf){raf(function(){tick=graceunderpressure_sticky_header(e,items,window.scrollY,lastScrollTop,wh);lastScrollTop=window.scrollY;});}else{setTimeout(function(){tick=graceunderpressure_sticky_header(e,items,window.scrollY,lastScrollTop,wh);lastScrollTop=window.scrollY;},16);}
tick=true;});}})(jQuery);}
function graceunderpressure_scroll_direction(event,lst){(function($){var st=window.scrollY;if(st>lst){if(st<=40){$('body').removeClass('scroll-up');$('body').removeClass('scroll-down');var mt=st;mt=mt-(2*mt);if((navigator.userAgent.indexOf('Safari')==-1||navigator.userAgent.indexOf('Chrome')!=-1)&&mt>0){mt=0;}
$('.navbar-toggle').css({'-webkittransform':'translate3d(0, '+ mt+'px, 0)','transform':'translate3d(0, '+ mt+'px, 0)',});}else{$('.navbar-toggle').removeAttr('style');$('body').removeClass('scroll-down');$('body').addClass('scroll-up');}}else{if(st<=0){var mt=st;mt=mt-(2*mt);if((navigator.userAgent.indexOf('Safari')==-1||navigator.userAgent.indexOf('Chrome')!=-1)&&mt>0){mt=0;}
$('.navbar-toggle').css({'-webkittransform':'translate3d(0, '+ mt+'px, 0)','transform':'translate3d(0, '+ mt+'px, 0)',});$('body').removeClass('scroll-up');$('body').removeClass('scroll-down');}else if(st<=40){if(!$('body').hasClass('scroll-down')){var mt=st;$('.navbar-toggle').css({'-webkittransform':'translate3d(0, -'+ mt+'px, 0)','transform':'translate3d(0, -'+ mt+'px, 0)',});}}else{$('body').removeClass('scroll-up');$('body').addClass('scroll-down');}}})(jQuery);return false;}
function graceunderpressure_toggle_swipe(){(function($){if($(window).width()>=1200){$('body').swipe('disable');}else{$('body').swipe('enable');}})(jQuery);return false;}
jQuery(document).ready(function($){var navbar_height=$('.site-header .container-fluid').outerHeight(),footer_height=$('.site-footer').outerHeight(),margin_top=navbar_height+ footer_height- $(window).height();$('.site-header').stick_in_parent();$('.navbar-nav .dropdown > a .caret').on('click',function(event){event.preventDefault();var dropdown=$(this).parent().parent();if(dropdown.hasClass('open')){dropdown.removeClass('open');}else{dropdown.addClass('open');}});var items=$('.blog.blog-design-blog .hentry');$('.blog.blog-design-blog .entry-header').stick_in_parent();$('.navbar-toggle').on('click',function(){$('body').toggleClass('navbar-visible');});$('.site-header, .site-footer').on('mousedown',function(event){var $this=$(this),target=$(event.target);if(target.hasClass('navbar-toggle')||target.hasClass('glyphicon-th')){return false;}
if(!$('body').hasClass('navbar-visible')){$('body').addClass('navbar-visible');$this.addClass('mousedown');setTimeout(function(){$this.removeClass('mousedown');},250);}});$('.navbar-hide').click(function(){if($('body').hasClass('navbar-visible')){$('body').removeClass('navbar-visible');}});if('undefined'!=typeof $.fn.swipe){var dir,rev;$('body').swipe({swipeStatus:function(event,phase,direction,distance){if($('body').hasClass('navbar-position-left')){dir='right';rev='left';}else{dir='left';rev='right';}
if(phase=='end'){if(direction==dir&&!$('body').hasClass('navbar-visible')){$('body').addClass('navbar-visible');}else if(direction==rev&&$('body').hasClass('navbar-visible')){$('body').removeClass('navbar-visible');}}},longTap:function(event,target){event.preventDefault();$(target).select();},allowPageScroll:'vertical',triggerOnTouchEnd:false,});if($(window).width()>=1200){$('body').swipe('disable');}
var tck=false;window.addEventListener('resize',function(event){if(!tck&&raf){raf(function(){tck=graceunderpressure_toggle_swipe();});}else{setTimeout(function(){tck=graceunderpressure_toggle_swipe();},16);}});}
var tick=false;var lst=0;window.addEventListener('scroll',function(event){var e=event;if(!tick&&raf){raf(function(){tick=graceunderpressure_scroll_direction(e,lst);lst=window.scrollY;});}else{setTimeout(function(){tick=graceunderpressure_scroll_direction(e,lst);lst=window.scrollY;},16);}
tick=true;});$('.more-link').on('click',graceunderpressure_ajax_state);$('#primary').on('enlightenment_infinite_scroll',function(event,items){if($('body').hasClass('blog-design-blog')){$('.entry-header',items).stick_in_parent();}
$('.more-link',items).on('click',graceunderpressure_ajax_state);});if(typeof wp!='undefined'&&typeof wp.customize!='undefined'&&typeof enlightenment_infinite_scroll_args!='undefined'){$(enlightenment_infinite_scroll_args.contentSelector).infinitescroll('destroy');}
var page_loaded=false;window.addEventListener('popstate',function(event){event.preventDefault();event.stopPropagation();if(navigator.userAgent.indexOf('Safari')!=-1&&navigator.userAgent.indexOf('Chrome')==-1&&!page_loaded){page_loaded=true;return false;}});});